# Generated by Django 2.2.7 on 2020-05-24 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
