# Generated by Django 2.2.7 on 2020-06-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0002_auto_20200524_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=30)),
                ('order_id', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=15)),
                ('date_issue', models.CharField(max_length=12)),
                ('source_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docdata.RawData')),
            ],
        ),
    ]
