# Generated by Django 2.2.7 on 2020-06-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0003_processeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='amount_due',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='amount_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='item_amount_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='item_description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='item_quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='recipient_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='recipient_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='sender_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='sender_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='processeddata',
            name='sender_vat_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='customer_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='date_issue',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='invoice_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='order_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
