# Generated by Django 2.2.7 on 2020-06-07 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0004_auto_20200607_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='RDRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docdata.RawData'),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='source_invoice',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
