# Generated by Django 2.2.7 on 2020-06-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0005_auto_20200607_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='RDRef',
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='source_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docdata.RawData'),
        ),
    ]
