# Generated by Django 2.2.7 on 2020-06-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0006_auto_20200607_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processeddata',
            old_name='source_invoice',
            new_name='source_file',
        ),
    ]
