# Generated by Django 2.2.7 on 2020-06-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0008_auto_20200607_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='item_amount_total',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
