# Generated by Django 2.2.7 on 2020-06-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0010_remove_processeddata_item_amount_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='item_quantity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
