# Generated by Django 2.2.7 on 2020-06-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0011_auto_20200607_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='item_quantity',
        ),
    ]
