# Generated by Django 2.2.7 on 2020-06-15 19:53

from django.db import migrations
import json_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0012_remove_processeddata_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='json_data',
            field=json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object'),
        ),
    ]
