# Generated by Django 2.2.7 on 2020-06-15 20:19

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0013_auto_20200616_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='json_data',
            field=jsonfield.fields.JSONField(),
        ),
    ]
