# Generated by Django 2.2.7 on 2020-06-15 20:19

from django.db import migrations
import json_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0014_auto_20200616_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='json_data',
            field=json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object'),
        ),
    ]
