# Generated by Django 2.2.7 on 2020-06-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0015_auto_20200616_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddata',
            name='item_description',
        ),
        migrations.AddField(
            model_name='processeddata',
            name='all_items',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, null=True)),
                ('item_quantity', models.FloatField(null=True)),
                ('item_total_amount', models.FloatField(null=True)),
                ('rawdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docdata.RawData')),
            ],
        ),
    ]
