# Generated by Django 2.2.7 on 2020-06-16 13:38

from django.db import migrations, models
import json_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0017_auto_20200616_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='device_transfer',
            field=json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object', null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='item_quantity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='item_total_amount',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='amount_due',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='amount_total',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
